---
env:
  contexts:
    - name: "Default Context"
      urls:
        - "http://example.com"  
      includePaths:
        - ".*"
      excludePaths: []
  parameters:
    failOnError: true
    progressToStdout: true
jobs:
  - type: spider
    parameters:
      context: "Default Context"
      maxDuration: 5
  - type: passiveScan-config
    parameters: {}  
  - type: passiveScan-wait
    parameters: {} 
  - type: activeScan
    parameters:
      context: "Default Context"
      maxRuleDurationInMins: 5
  - type: report
    parameters:
      template: "traditional-html"
      reportDir: ""
      reportFile: "report"
      reportTitle: "ZAP DAST Report"
      reportDescription: ""