name: CI DevSecBackend

on:
  pull_request:
    branches:
      - main

jobs:
  full-branch-scan:
    name: Full SonarCloud Analysis Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test backend with Maven
        run: mvn clean verify --file ./pom.xml

      - name: Run Checkstyle (format test)
        run: mvn checkstyle:check --file ./pom.xml

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Fedex95_DevSecOpsBack
            -Dsonar.organization=daslicht
            -Dsonar.branch.name=main

      - name: Fail if critical/blocker issues exist
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          CRITICAL_ISSUES=$(curl -s -u $SONAR_TOKEN: \
            "https://sonarcloud.io/api/issues/search?componentKeys=Fedex95_DevSecOpsBack&severities=CRITICAL,BLOCKER" \
            | jq '.total')
          echo "Critical/Blocker issues in main: $CRITICAL_ISSUES"
          if [ "$CRITICAL_ISSUES" -gt 0 ]; then
            echo "Failing CI due to critical/blocker issues in main"
            exit 1
          fi

      - name: Upload target report
        uses: actions/upload-artifact@v4
        with:
          name: target-report
          path: target/
