name: CI DevSecBackend

permissions:
  contents: write
  pull-requests: write
  security-events: write

on:
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and test backend with Maven
        run: mvn clean verify --file ./pom.xml

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/setup@master
      
      - name: Run SCA with Snyk (Maven)
        run: snyk test --package-manager=maven --file=pom.xml --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run SCA with Snyk (npm)
        run: snyk test --file=package.json --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Checkstyle (format test)
        run: mvn checkstyle:check --file ./pom.xml
      
      - name: Upload target report
        uses: actions/upload-artifact@v4
        with:
          name: target-report
          path: target/