name: CI DevSecBackend

permissions:
  contents: write
  pull-requests: write
  security-events: write

on:
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Setup Maven
        run: |
          chmod +x mvnw
          ./mvnw --version

      - name: Build and test backend with Maven
        run: ./mvnw clean verify --file ./pom.xml

      - name: Run SCA with Snyk (Maven)
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
        with:
          command: test
          args: >-
            --severity-threshold=medium
            --package-manager=maven
            --file=pom.xml

      - name: Run SCA with Snyk (npm)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >-
            --severity-threshold=medium
            --file=package.json

      - name: Run Checkstyle (format test)
        run: ./mvnw checkstyle:check --file ./pom.xml
      
      - name: Upload target report
        uses: actions/upload-artifact@v4
        with:
          name: target-report
          path: target/